// Cyber City territories — 6 zones with invader factions, modifiers, decks
// See design doc 01-territories.md for the full roster

export const TERRITORIES = {
  neon_bazaar: {
    id: 'neon_bazaar',
    name: 'Neon Bazaar',
    domain: 'Red',
    invader: 'Black',
    tier: 1,
    description: 'Sprawling night market — smugglers move contraband through Red turf.',
    modifier: null,
    decayRate: 1.0,
    resourceBias: { ore: 1.0, credits: 1.0 },
    unlockedAtStart: true,
  },
  spire_districts: {
    id: 'spire_districts',
    name: 'Spire Districts',
    domain: 'Red',
    invader: 'White',
    tier: 1,
    description: 'Glass-and-chrome corporate towers casting shadows on the streets.',
    modifier: 'corporate_audit',
    decayRate: 1.0,
    resourceBias: { ore: 0.9, credits: 1.2 },
    unlockedAtStart: true,
  },
  foundry: {
    id: 'foundry',
    name: 'The Foundry',
    domain: 'Red',
    invader: 'Black',
    tier: 2,
    description: 'Industrial mining complex — smoke and rust beneath the neon.',
    modifier: 'forge_heat',
    decayRate: 1.0,
    resourceBias: { ore: 1.25, credits: 0.85 },
    unlockedAtStart: true,
  },
  static_junkyard: {
    id: 'static_junkyard',
    name: 'Static Junkyard',
    domain: 'Red',
    invader: 'Black',
    tier: 2,
    description: 'Piles of corrupted card data and broken hardware. Scavengers picking the bones.',
    modifier: 'salvage',
    decayRate: 1.5,
    resourceBias: { ore: 1.1, credits: 1.0 },
    unlockedAtStart: true,
  },
  pulse_cathedral: {
    id: 'pulse_cathedral',
    name: 'Pulse Cathedral',
    domain: 'Red',
    invader: 'White',
    tier: 3,
    description: 'A converted nightclub — the White faction is purifying it back into a cathedral.',
    modifier: 'sanctified_ground',
    decayRate: 1.0,
    resourceBias: { ore: 0.85, credits: 1.3 },
    unlockedAtStart: true,
  },
  aether_nexus: {
    id: 'aether_nexus',
    name: 'Aether Nexus',
    domain: 'Red',
    invader: 'Purple',
    tier: 3,
    description: 'A reality tear in the heart of Red — the Veil Conclave is bleeding through.',
    modifier: 'reality_drift',
    decayRate: 1.5,
    resourceBias: { ore: 1.0, credits: 1.0 },
    unlockedAtStart: false,
    unlockGate: { type: 'others_at_75', count: 4 },
  },
};
